### ISSUE TITLE
Magic mismatch. EspFS image broken"

### ISSUE THREAD

**Issue by valkuc** [Spritetm/esphttpd#6] opened 2016-03-24 01:29 UTC

**Comment by Spritetm** [comment] 2016-03-24 01:33
Yes, that is a string that exists within the esphttpd codebase. What of it? Is there a typo in it or something?

**Comment by valkuc** [comment] 2016-03-24 01:38
Hello.
I'm having "Magic mismatch. EspFS image broken." when trying to access file by URL.
Call to "espFsInit" return 0 in user_init. I also have retrieved my esfs content from flash and compared it with original - they same. I'm guess that issue somewhere in esfs. A little debugging shown me that resulting value of "h.magic" in espfs.c method "espFsOpen" gives value "-418771509" (DEC) while expected value is "0x73665345" (HEX). Now if we convert both value to binary form we will have next:
`Actual: 1111111111111111111111111111111111100111000010100000110111001011`
`Expected: 1110011011001100101001101000101`
(read them from right to left)
As you can see it looks like we start reading FS header at wrong position (exactly +1 byte).

---

P.S.
Sorry was mistakenly pressed Ctrl+Enter - as result first post was empty.

**Comment by Spritetm** [comment] 2016-03-24 01:43
How are you compiling esphttpd? Combined, ota or separate?

**Comment by Spritetm** [comment] 2016-03-24 01:48
Also, maybe I'm miscalculating it, but -418771509 in hex is e70a0dcb which doesn't seem to me like 0x73665345 offset by one.

**Comment by valkuc** [comment] 2016-03-24 01:51
Well maybe I'm wrong about "1 byte offset" - looking second time at this binary sequence and getting confused. I'm compiling it totally standalone inside my project as lib. HTML files is uploaded at fixed address 0x18000. I also have tryed to compile espfstest to check maybe the problem in mkespfsimage but it not compiling because recent espfs use spi_flash_read/write functions and not compiling as standalone app.

**Comment by Spritetm** [comment] 2016-03-24 01:55
Ah, the non-compiling of the test program is an issue that should be fixed. I highly doubt the espfs is the problem, though. If you still want to check, the 'magic number' basically is 'ESfs'. so if you use a hexeditor on webpages.espfs and see these letters as the first 4 characters, you at least know the espfs file is mostly sane. 
Are you sure you're not overwriting the espfs with your executable code by the way?

**Comment by valkuc** [comment] 2016-03-24 01:57
Another moment if use mkespfsimage supplied in UDK - https://github.com/CHERTS/esp8266-devkit/tree/master/Espressif/examples/ESP8266/ESP8266_Relay_Board/mkespfsimage this issue is not reproduced, but this code a bit outdated so I decided to use code from your repository and compiled mkespfsimage tool (and of course eshttpd itself) by myself and now getting this problem.

**Comment by Spritetm** [comment] 2016-03-24 01:58
Can you upload the webpages.espfs compiled by both versions of the mkespfsimage somewhere?

**Comment by valkuc** [comment] 2016-03-24 02:05
I'm sure I'm not overwriting FS by my code because I have issued "esptool.exe -p COM3 -b 115200 read_flash 0x18000 0x28000 build/webpages.espfs1" and compared it with original that I was flashed - they same (at least if comparing from beginning to the end of original file) and both have "ESfs" signature.

**Comment by valkuc** [comment] 2016-03-24 02:06
Here are they [link removed]
One is compiled with tool supplied with UDK, another one with newest version from git. Please tell me when you download file so I remove public link to my personal home server :)

**Comment by valkuc** [comment] 2016-03-24 02:15
And here is two diffs in those files.
![diff1](https://cloud.githubusercontent.com/assets/6421082/14006548/ca696984-f187-11e5-9114-9f6c16ef73c7.PNG)
![diff2](https://cloud.githubusercontent.com/assets/6421082/14006551/cf031e68-f187-11e5-9f18-51ea0daf5147.PNG)

**Comment by Spritetm** [comment] 2016-03-24 02:16
I'm not sure what you did with the poor espfs file, but I see that the new one has all the 0x0a (LF) characters converted to CR/LF pairs. What OS are you running this on?

**Comment by valkuc** [comment] 2016-03-24 02:21
Here is also online comparison - https://www.diffnow.com/?report=xpkbz
I'm using Win7, but compile from mingw

**Comment by Spritetm** [comment] 2016-03-24 02:24
Hmm. I think there is something you do that treats the espfs file as a text file, doing you the dubious favour of converting all the line-ends to Windows-style CR/LFs for you, thereby messing up the format of the file. As far as I know, mkespfsimage itself does everything binary; I also do not have a Windows machine to test this on though. In other words: I can't reproduce it, but if you find out what causes this and it's in my code, I'll be glad to fix it.

**Comment by Spritetm** [comment] 2016-03-24 02:26
Not sure if you use it, but according to https://cygwin.com/cygwin-ug-net/using-textbinary.html, adding O_BINARY to the flags used in the open() call can fix it. Maybe you can try that?

**Comment by valkuc** [comment] 2016-03-24 02:27
Sure, give me few mins

**Comment by Spritetm** [comment] 2016-03-24 02:34
Seems a bit more is needed (stdout also has to be binary). Could you try replacing the main.c of mkespfsimage with this one: http://meuk.spritesserver.nl/main.c and retrying?

**Comment by valkuc** [comment] 2016-03-24 02:36
Yes, just adding O_BINARY have not helped. Trying your main.c

**Comment by valkuc** [comment] 2016-03-24 02:43
Hm... nothing changed. Same extra 0xOD added

**Comment by Spritetm** [comment] 2016-03-24 02:45
What toolchain do you use? mingw, cygwin, ...?

**Comment by valkuc** [comment] 2016-03-24 02:49
I'm using MINGW... Solved - here is updated file - [link removed]
I also removed include arpa.h

**Comment by valkuc** [comment] 2016-03-24 02:50
Just checked on ESP - now all ok, issue solved. Thank you.

**Comment by Spritetm** [comment] 2016-03-24 02:51
Check, I'll include your modifications in the main repo. Thanks for helping solve this!

**Closed as completed** 2016-03-24 02:52 UTC
